import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { supabaseAdmin } from "@/lib/supabase-client";

function getOpenAI() { return new OpenAI({ apiKey: process.env.OPENAI_API_KEY }); }

export async function POST(req: NextRequest) {
  try {
    const { personaDescription } = await req.json();

    if (!personaDescription) {
      return NextResponse.json({ error: "Missing persona description" }, { status: 400 });
    }

    const response = await getOpenAI().images.generate({
      model: "dall-e-3",
      prompt: `${personaDescription}
      
      TECHNICAL REQUIREMENTS:
      - Photorealistic professional headshot
      - Studio photography with high-end lighting
      - 4K quality, sharp facial details
      - Magazine cover aesthetic
      - Natural makeup, professional styling
      - Clean background, minimal distractions
      - Instagram influencer standard`,
      size: "1024x1024",
      quality: "hd",
      n: 1,
    });

    const openaiImageUrl = response.data?.[0]?.url;
    if (!openaiImageUrl) throw new Error("No image generated by DALL-E");

    // Download image from OpenAI
    const imgRes = await fetch(openaiImageUrl);
    if (!imgRes.ok) throw new Error("Failed to download image from OpenAI");
    const imgBuffer = await imgRes.arrayBuffer();

    // Upload to Supabase Storage (media bucket)
    const filePath = `influencers/persona-${Date.now()}-${Math.random().toString(36).substring(7)}.png`;
    
    // Fallback if supabase fails (e.g., config not fully setup)
    let finalImageUrl = openaiImageUrl;
    
    if (process.env.SUPABASE_SERVICE_ROLE_KEY) {
      const { data: uploadData, error: uploadError } = await supabaseAdmin
        .storage
        .from("media")
        .upload(filePath, imgBuffer, { contentType: "image/png" });
        
      if (!uploadError) {
        // Get public URL
        const { data: publicUrlData } = supabaseAdmin.storage.from("media").getPublicUrl(filePath);
        finalImageUrl = publicUrlData.publicUrl;
      } else {
        console.error("Supabase upload failed, falling back to OpenAI URL:", uploadError);
      }
    }

    return NextResponse.json({ success: true, imageUrl: finalImageUrl });
  } catch (err: any) {
    console.error("Image generation failed:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
