"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight, CheckCircle2, Sparkles, ChevronDown, ChevronUp } from "lucide-react";
import Link from "next/link";

// ── Mock data — simulates personas + products already created ─────────────────
const MOCK_INFLUENCERS = [
  { id: "ava", name: "Ava Chen (@ava.moves)" },
  { id: "marcus", name: "Marcus Reid (@marcuslifts)" },
  { id: "priya", name: "Priya Nair (@runwithpriya)" },
  { id: "jordan", name: "Jordan Ellis (@jordo.daily)" },
];

const MOCK_PRODUCTS = [
  { id: "align", name: "Lululemon Align Pant" },
  { id: "define", name: "Lululemon Define Jacket" },
  { id: "swiftly", name: "Lululemon Swiftly Tech Racerback" },
  { id: "abc", name: "Lululemon ABC Pant" },
];

// ── Mock scripts generated by "Claude" ───────────────────────────────────────
const SCRIPTS = [
  {
    id: "pain",
    angle: "Pain-point",
    tag: "Highest converter",
    hook: "\"If your leggings are distracting you mid-flow, they're already failing you.\"",
    body: "Ava slips into her Align Pants at sunrise. The camera lingers on the buttery-soft fabric as she moves through a Warrior sequence — no adjusting, no readjusting. VO: \"The Align Pant was designed for one thing: to disappear. 28\" of Nulu fabric so light you'll forget you're wearing them — until you PR your class.\"",
    cta: "\"Get yours at lululemon.com — link in bio.\"",
    duration: "0:00–0:28",
  },
  {
    id: "lifestyle",
    angle: "Lifestyle",
    tag: "Brand awareness",
    hook: "\"This is what 6am looks like when you actually love your routine.\"",
    body: "Montage: Ava's alarm at 5:58am, coffee pour, lacing up shoes, stepping onto the mat. The Align Pant threads through every scene. VO: \"Morning practice isn't a chore when your gear moves with you. Lululemon Align — built for the life you're already living.\"",
    cta: "\"Shop the Align collection — link in bio.\"",
    duration: "0:00–0:27",
  },
  {
    id: "social",
    angle: "Social proof",
    tag: "Trust builder",
    hook: "\"I've tried 11 leggings. I stopped looking after these.\"",
    body: "Ava holds up the Align Pant to camera, then demonstrates the 4-way stretch. Text overlays: \"2.1M yogis agree\" → \"#1 on Lululemon's best-seller list for 3 years\" → \"4.9★ across 48,000 reviews\". VO: \"There's a reason these sell out every drop. I'm not the only one who noticed.\"",
    cta: "\"Tap the link — they go fast.\"",
    duration: "0:00–0:29",
  },
];

type Status = "idle" | "loading" | "success";

export default function NewScriptPage() {
  const [influencer, setInfluencer] = useState("");
  const [product, setProduct] = useState("");
  const [extraContext, setExtraContext] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [selectedScript, setSelectedScript] = useState<string>("pain");
  const [expandedScript, setExpandedScript] = useState<string | null>("pain");
  const [error, setError] = useState("");

  const hasInfluencers = MOCK_INFLUENCERS.length > 0;
  const hasProducts = MOCK_PRODUCTS.length > 0;

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (!influencer) { setError("Please select an influencer persona."); return; }
    if (!product) { setError("Please select a product."); return; }

    setStatus("loading");
    setTimeout(() => {
      setStatus("success");
    }, 2000);
  }

  const chosenInfluencer = MOCK_INFLUENCERS.find((i) => i.id === influencer);
  const chosenProduct = MOCK_PRODUCTS.find((p) => p.id === product);
  const chosen = SCRIPTS.find((s) => s.id === selectedScript) ?? SCRIPTS[0];

  // ── Success state ──────────────────────────────────────────────────────────
  if (status === "success") {
    return (
      <div className="px-10 py-10 max-w-2xl">
        <p className="label-section mb-3">Step 3 of 4 — Complete</p>
        <div className="flex items-center gap-2 mb-2">
          <CheckCircle2 className="h-6 w-6" style={{ color: "var(--primary)" }} />
          <h1 className="text-3xl font-extrabold tracking-tight" style={{ color: "var(--foreground)" }}>
            3 scripts generated!
          </h1>
        </div>
        <p className="text-[14px] mb-8" style={{ color: "var(--foreground-muted)" }}>
          Select the angle you want to use — then render your video.
        </p>

        {/* Script cards */}
        <div className="space-y-3 mb-8">
          {SCRIPTS.map((script) => {
            const isSelected = selectedScript === script.id;
            const isExpanded = expandedScript === script.id;
            return (
              <div
                key={script.id}
                className="rounded-xl overflow-hidden transition-all cursor-pointer"
                style={{
                  border: `1.5px solid ${isSelected ? "var(--primary)" : "var(--border)"}`,
                  background: isSelected ? "var(--primary-subtle)" : "var(--background-card)",
                }}
                onClick={() => setSelectedScript(script.id)}
              >
                <div className="px-5 py-4 flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3 flex-1 min-w-0">
                    {/* Radio dot */}
                    <div
                      className="mt-0.5 h-4 w-4 rounded-full border-2 flex-shrink-0 flex items-center justify-center transition-colors"
                      style={{
                        borderColor: isSelected ? "var(--primary)" : "var(--border)",
                        background: isSelected ? "var(--primary)" : "transparent",
                      }}
                    >
                      {isSelected && <div className="h-1.5 w-1.5 rounded-full bg-white" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap mb-1">
                        <span className="text-[14px] font-bold" style={{ color: "var(--foreground)" }}>
                          {script.angle}
                        </span>
                        <span
                          className="text-[10px] font-semibold px-2 py-0.5 rounded-full"
                          style={{ background: "var(--primary-subtle)", color: "var(--primary)" }}
                        >
                          {script.tag}
                        </span>
                      </div>
                      <p className="text-[12px] italic leading-snug line-clamp-2" style={{ color: "var(--foreground-muted)" }}>
                        {script.hook}
                      </p>
                    </div>
                  </div>
                  <button
                    className="flex-shrink-0 mt-0.5 transition-opacity hover:opacity-60"
                    style={{ color: "var(--foreground-muted)" }}
                    onClick={(e) => {
                      e.stopPropagation();
                      setExpandedScript(isExpanded ? null : script.id);
                    }}
                  >
                    {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                  </button>
                </div>

                {/* Expanded body */}
                {isExpanded && (
                  <div
                    className="px-5 pb-5 space-y-3 text-[12px] leading-relaxed"
                    style={{ borderTop: "1px solid var(--border)", paddingTop: "1rem" }}
                  >
                    <div>
                      <span className="font-semibold" style={{ color: "var(--foreground)" }}>Body: </span>
                      <span style={{ color: "var(--foreground-muted)" }}>{script.body}</span>
                    </div>
                    <div>
                      <span className="font-semibold" style={{ color: "var(--foreground)" }}>CTA: </span>
                      <span style={{ color: "var(--foreground-muted)" }}>{script.cta}</span>
                    </div>
                    <div>
                      <span className="font-semibold" style={{ color: "var(--foreground)" }}>Timing: </span>
                      <span style={{ color: "var(--foreground-muted)" }}>{script.duration}</span>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Next step CTA */}
        <div
          className="rounded-xl p-5 mb-4"
          style={{ background: "var(--primary-subtle)", border: "1px solid var(--border)" }}
        >
          <p className="text-[13px] font-semibold mb-1" style={{ color: "var(--foreground)" }}>
            Next: render your video
          </p>
          <p className="text-[12px] mb-3" style={{ color: "var(--foreground-muted)" }}>
            Using <strong>{chosenInfluencer?.name}</strong>, the <strong>{chosen.angle}</strong> script,
            and <strong>{chosenProduct?.name}</strong>.
          </p>
          <Link href="/videos/new">
            <Button size="lg">
              Render video
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>

        <button
          onClick={() => setStatus("idle")}
          className="text-[12px] transition-opacity hover:opacity-60"
          style={{ color: "var(--foreground-muted)" }}
        >
          ← Generate with different settings
        </button>
      </div>
    );
  }

  // ── Form state ─────────────────────────────────────────────────────────────
  return (
    <div className="px-10 py-10 max-w-xl">

      <Link
        href="/scripts"
        className="inline-flex items-center gap-1.5 text-[13px] font-medium mb-8 transition-opacity hover:opacity-60"
        style={{ color: "var(--foreground-muted)" }}
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Scripts
      </Link>

      <p className="label-section mb-3">Step 3 of 4</p>
      <h1
        className="text-3xl font-extrabold tracking-tight"
        style={{ color: "var(--foreground)" }}
      >
        Generate scripts
      </h1>
      <p className="mt-2 text-[15px] leading-relaxed" style={{ color: "var(--foreground-muted)" }}>
        Claude writes 3 script options — pain-point, lifestyle, and social proof angles. Each includes a hook, benefit statement, CTA, and exact timing for voiceover sync.
      </p>

      {/* Loading state */}
      {status === "loading" && (
        <div
          className="mt-8 rounded-xl p-8 text-center"
          style={{ background: "var(--background-card)", border: "1px solid var(--border)" }}
        >
          <div className="flex justify-center mb-4">
            <Sparkles className="h-8 w-8 animate-pulse" style={{ color: "var(--primary)" }} />
          </div>
          <p className="text-[15px] font-semibold" style={{ color: "var(--foreground)" }}>
            Claude is writing your scripts…
          </p>
          <p className="text-[13px] mt-1.5" style={{ color: "var(--foreground-muted)" }}>
            Generating 3 angles: pain-point, lifestyle, and social proof
          </p>
          <div className="mt-5 flex justify-center gap-1.5">
            {[0, 1, 2].map((i) => (
              <div
                key={i}
                className="h-2 w-2 rounded-full animate-bounce"
                style={{ background: "var(--primary)", animationDelay: `${i * 0.15}s` }}
              />
            ))}
          </div>
        </div>
      )}

      {status === "idle" && (
        <form className="mt-10 space-y-6" onSubmit={handleSubmit}>
          {/* Influencer select */}
          <div className="space-y-1.5">
            <label htmlFor="influencer" className="block text-[13px] font-semibold" style={{ color: "var(--foreground)" }}>
              Influencer persona
            </label>
            {hasInfluencers ? (
              <select
                id="influencer"
                value={influencer}
                onChange={(e) => setInfluencer(e.target.value)}
                className="w-full rounded-lg border px-3.5 py-2.5 text-sm outline-none transition-shadow focus:ring-2 focus:ring-[var(--primary-ring)]"
                style={{ background: "var(--background-card)", borderColor: "var(--border)", color: "var(--foreground)" }}
              >
                <option value="">Select influencer…</option>
                {MOCK_INFLUENCERS.map((inf) => (
                  <option key={inf.id} value={inf.id}>{inf.name}</option>
                ))}
              </select>
            ) : (
              <div
                className="rounded-lg border px-3.5 py-3 text-[13px]"
                style={{ background: "var(--background-card)", borderColor: "var(--border)", color: "var(--foreground-muted)" }}
              >
                No personas yet.{" "}
                <Link href="/influencers/new" className="underline font-semibold" style={{ color: "var(--primary)" }}>
                  Create one first →
                </Link>
              </div>
            )}
          </div>

          {/* Product select */}
          <div className="space-y-1.5">
            <label htmlFor="product" className="block text-[13px] font-semibold" style={{ color: "var(--foreground)" }}>
              Product
            </label>
            {hasProducts ? (
              <select
                id="product"
                value={product}
                onChange={(e) => setProduct(e.target.value)}
                className="w-full rounded-lg border px-3.5 py-2.5 text-sm outline-none transition-shadow focus:ring-2 focus:ring-[var(--primary-ring)]"
                style={{ background: "var(--background-card)", borderColor: "var(--border)", color: "var(--foreground)" }}
              >
                <option value="">Select product…</option>
                {MOCK_PRODUCTS.map((prod) => (
                  <option key={prod.id} value={prod.id}>{prod.name}</option>
                ))}
              </select>
            ) : (
              <div
                className="rounded-lg border px-3.5 py-3 text-[13px]"
                style={{ background: "var(--background-card)", borderColor: "var(--border)", color: "var(--foreground-muted)" }}
              >
                No products yet.{" "}
                <Link href="/products/new" className="underline font-semibold" style={{ color: "var(--primary)" }}>
                  Upload one first →
                </Link>
              </div>
            )}
          </div>

          <div className="space-y-1.5">
            <label htmlFor="extra-context" className="block text-[13px] font-semibold" style={{ color: "var(--foreground)" }}>
              Extra context <span className="font-normal" style={{ color: "var(--foreground-muted)" }}>(optional)</span>
            </label>
            <textarea
              id="extra-context"
              rows={3}
              value={extraContext}
              onChange={(e) => setExtraContext(e.target.value)}
              placeholder="e.g. Emphasise the limited colourway drop. Avoid mentioning competitor brands."
              className="w-full rounded-lg border px-3.5 py-2.5 text-sm outline-none transition-shadow focus:ring-2 focus:ring-[var(--primary-ring)] resize-none"
              style={{ background: "var(--background-card)", borderColor: "var(--border)", color: "var(--foreground)" }}
            />
          </div>

          {error && (
            <p className="text-[13px] font-medium" style={{ color: "var(--destructive)" }}>
              {error}
            </p>
          )}

          <div className="pt-2 flex items-center gap-3">
            <Button type="submit" size="lg" disabled={!hasInfluencers || !hasProducts}>
              <Sparkles className="h-4 w-4" />
              Generate 3 scripts
            </Button>
            <Link href="/scripts">
              <Button variant="ghost" size="lg">Cancel</Button>
            </Link>
          </div>
        </form>
      )}
    </div>
  );
}
